### ISSUE TITLE
[counter] improvement

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#113]
[counter] object should have a @set property to be able to set the curent value.
also [flow.count] have @value property, but only accepts "bang".

**Comment by uliss** [comment]
> [counter] object should have a @set property to be able to set the curent value.
> also [flow.count] have @value property, but only accepts "bang".

I think that **set** should be a message, like `[set(`, and `[seq.counter]` should have `@value` property to change its value.

I this moment `[flow.count]` and all others **flow.*** object properties can be set, but not directly by sending them messages, like `[@prop VALUE(`, because flow objects are dealing with any message type, for example `[flow.count]` should count any message, even `[@value X(`. 

Now getting/setting any property from flow object can be done with `[prop.get/set]` objects.
Looks like: 
<img width="308" alt="Снимок экрана 2021-03-12 в 2 47 01" src="https://user-images.githubusercontent.com/350661/110870400-680d0880-82dd-11eb-9d0a-600666a32aa8.png">

But I agree that `[flow.count]` right inlet should support `[@value(` messages also and this will be added.

**Comment by 60-hz** [comment]
> I think that set should be a message, like [set(, and [seq.counter] should have @value property to change its value.

I agree, @value is ok, "set" is also a common method in pd so it makes sense too.
But then there will 2 ways to change the internal object state? (I am ok with it).

I am not always sure about the use of [flow.count], because all flow object are about something going through them, and [flow.cont] is more of a content generator function.

As a result, it seems to be redundant with [seq.counter]. For sanity, I would keep only [counter] function in order to keep the objects number as low as possible.

**Comment by uliss** [comment]
As I see, the `flow.count` should count every incoming message. It's not really a generator/sequencer. It's a general purpose object to work with data flow.
But `seq.counter` - is a sequence producer, it doesnt count infinitely, it's domain specific object, to use for music generation. It can control repeats, so you can play sequence (as with other seq.* objects) specified number of times.

**Comment by 60-hz** [comment]
Ok, I got it.
I didn't noticed [counter] / [seq.counter] couldn't count infinitely... I thought it was a nice  useful replacement for [cyclone/counter], because it's a very basic multi purpose object. But then If we want to have classic [counter] feature  it's not possible anymore because of name clash. So for best compatibility, I think ceammc [counter] should have same feature as other counter, at least counting infinitely without argument (an object which return 0  without arg is not very useful) and [set] message / @value.

**Comment by uliss** [comment]
Yes, `[seq.counter]` was not intended to replace `[cyclone/counter]` 
But `[seq.counter]` can count infinitely if you set `@r` property to -1, or using `@inf` flag. The idea was to make unified interface to seq.* objects.

May be we can find more sutable name for `[seq.counter]`. And to avoid name clashes with cyclone we will remove `[counter]` alias.

**Comment by 60-hz** [comment]
> But [seq.counter] can count infinitely if you set @r property to -1, or using @inf flag.

Great.

I think only removing only [counter] alias would be ok for name clash in most of using case yes.

**Comment by uliss** [comment]
fixed in previous release, closing

**Comment by 60-hz** [comment]
I see that [seq.counter] is still missing @value property in 0.9.4 and this would be nice to add it.

**Comment by 60-hz** [comment]
also [seq.counter] and [flow.count] could be greatly improved with  [inc(  and [dec( messages to choose explicit directions.
